### ISSUE TITLE
Roadmap to MVP

### ISSUE THREAD

**Issue by erik-lundgren** [erik-lundgren/octo-slack-bot#1]
# MVP
### Deploy
```
deploy <project> [<version>|<release>] [to <environment>]
```
Deploys latest release for a specified project to production. Or deploy the specified version/release to the specified environment if either are defined. If version is defined, create a new release with that version. Bot should confirm with the parameters it parsed and start the specified deploy without any additional user action.

### Abort
```
abort
```
Aborts all deploys triggered by the current user and prints the deploys it tried to abort as well as the success status of the aborts.

### Rollback
```
rollback <project>
```
Rolls back whatever is currently deployed to the last sucessful deploy for the specified project on "production" environment.

## Check 'em
- [ ] `deploy <project>`
- [ ] `abort`
- [ ] `rollback <project>`
- [ ] `deploy <project> <release>`
- [ ] `deploy <project> <version>`
- [ ] `deploy <project> to <environment>`
- [ ] `deploy <project> <release> to <environment>`
- [ ] `deploy <project> <version> to <environment>`

**Comment by erik-lundgren** [comment]
https://api.slack.com/docs/message-menus
